### Variables
@baseUrl = http://localhost:3001

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@test.com",
  "password": "12345_Aa"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "12345_Aa"
}

### Logout
POST {{baseUrl}}/auth/logout

### Get me
GET {{baseUrl}}/me

### Update email
PUT {{baseUrl}}/me/update-email
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "12345_Aa"
}