services:
  postgres:
    image: postgres:18
    container_name: books-authentication-db
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:7
    container_name: books-authentication-redis
    ports:
      - ${REDIS_PORT}:6379
